# Generated by Django 4.2.27 on 2026-01-31 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique identifier for the employee', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the employee', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the employee', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('department', models.CharField(help_text='Department the employee belongs to', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
